# Generated by Django 5.0.1 on 2024-03-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
    ]
