# Generated by Django 5.0.1 on 2024-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_counter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
