# Generated by Django 5.0.1 on 2024-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_counter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
