# Generated by Django 5.0.1 on 2024-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_counter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='img',
            field=models.CharField(default='images/Product-', max_length=200),
        ),
    ]
