# Generated by Django 5.0.1 on 2024-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_counter_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='img',
            field=models.CharField(default='images/Placeholder.png', max_length=200),
        ),
    ]
