# Generated by Django 5.0.1 on 2024-03-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_counter_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Product',
        ),
    ]
