# Generated by Django 5.0.1 on 2024-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orderPrice',
            field=models.IntegerField(default=0),
        ),
    ]
