# Generated by Django 4.2.3 on 2024-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_user_orderprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.BooleanField(default=0),
        ),
    ]
