# Generated by Django 4.2.3 on 2024-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
