# Generated by Django 4.2.3 on 2024-05-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_remove_customer_wishlist_remove_product_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.CreateModel(
            name='WishlistItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(default=0)),
                ('whislist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.wishlist')),
            ],
        ),
    ]
