# Generated by Django 4.2.3 on 2024-05-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_alter_wishlistitem_whislist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='whislist',
            new_name='whishlist',
        ),
    ]
