# Generated by Django 4.2.3 on 2024-05-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_alter_wishlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.product'),
        ),
    ]
