# Generated by Django 4.2.3 on 2024-05-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_wishlistitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='products',
            new_name='product_details',
        ),
    ]
