# Generated by Django 4.2.3 on 2024-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_rename_products_wishlistitem_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_details',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='img',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
