# Generated by Django 4.2.3 on 2024-05-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
