# Generated by Django 4.2.3 on 2024-05-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0052_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orderPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
    ]
