# Generated by Django 4.2.3 on 2024-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_remove_customer_cart_remove_customer_orderprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.IntegerField(default=0),
        ),
    ]
