# Generated by Django 4.2.3 on 2024-06-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='name',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.product'),
        ),
    ]
