# Generated by Django 4.2.3 on 2024-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_remove_wishlistitem_name_wishlistitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
