# Generated by Django 4.2.3 on 2024-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0059_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
