# Generated by Django 4.2.3 on 2024-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_customer_num_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='num_items',
        ),
        migrations.AddField(
            model_name='customer',
            name='order_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
