# Generated by Django 4.2.3 on 2024-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_remove_customer_cart_remove_customer_num_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
