# Generated by Django 4.2.3 on 2024-06-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0062_remove_orderitem_user_alter_customer_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num_items',
        ),
    ]
