# Generated by Django 4.2.3 on 2024-06-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
