# Generated by Django 4.2.3 on 2024-06-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_remove_order_completed_alter_wishlistitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_num',
        ),
    ]
