# Generated by Django 4.2.3 on 2024-06-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0068_customer_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_num',
        ),
    ]
